---
name: CI

on:
  push:
    branches: [ "master", "v*" ]
  pull_request:
    branches: [ "master", "v*" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    # 20.04 because https://github.com/actions/python-versions
    # does not have 2.7 and 3.6 binaries for 22.04.
    runs-on: "ubuntu-20.04"
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "2.7"
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11-dev"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"
          cache: "pip"
      - name: "Update pip"
        run: python -m pip install --upgrade pip setuptools wheel
      - name: "Install tox dependencies"
        run: python -m pip install --upgrade tox tox-gh-actions
      - name: "Run tox for ${{ matrix.python-version }}"
        run: "python -m tox"
